import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#95002a",
          container: "#be123c",
          fixed: "#ffdadb",
          "fixed-dim": "#ffb2b7",
          "on-fixed": "#40000d",
          "on-fixed-variant": "#920029",
        },
        secondary: {
          DEFAULT: "#4059aa",
          container: "#8fa7fe",
          fixed: "#dce1ff",
          "fixed-dim": "#b6c4ff",
          "on-fixed": "#00164e",
          "on-fixed-variant": "#264191",
        },
        tertiary: {
          DEFAULT: "#005338",
          container: "#006e4b",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
          "on-fixed": "#002113",
          "on-fixed-variant": "#005236",
        },
        background: "#f7f9fb",
        surface: {
          DEFAULT: "#f7f9fb",
          bright: "#f7f9fb",
          dim: "#d8dadc",
          variant: "#e0e3e5",
          container: {
            lowest: "#ffffff",
            low: "#f2f4f6",
            DEFAULT: "#eceef0",
            high: "#e6e8ea",
            highest: "#e0e3e5",
          },
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#ffd0d2",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#1d3989",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#67f4b7",
        "on-surface": {
          DEFAULT: "#191c1e",
          variant: "#5b4041",
        },
        outline: {
          DEFAULT: "#8f6f70",
          variant: "#e3bdbf",
        },
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
          "on-container": "#93000a",
        },
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        margin: "2rem",
        "margin-mobile": "1rem",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["'Be Vietnam Pro'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Be Vietnam Pro'", "sans-serif"],
        "body-md": ["'Be Vietnam Pro'", "sans-serif"],
        "body-lg": ["'Be Vietnam Pro'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      boxShadow: {
        card: "0 4px 20px -2px rgba(149, 0, 42, 0.06), 0 2px 6px -1px rgba(0, 0, 0, 0.03)",
        "card-hover": "0 16px 36px -4px rgba(149, 0, 42, 0.14), 0 6px 16px -2px rgba(0, 0, 0, 0.06)",
        sm: "0 2px 8px rgba(0, 0, 0, 0.04)",
        md: "0 4px 16px rgba(0, 0, 0, 0.06)",
        lg: "0 8px 24px rgba(0, 0, 0, 0.08)",
        xl: "0 12px 32px rgba(0, 0, 0, 0.12)",
      },
    },
  },
  plugins: [],
};

export default config;
